[package]
name = "spark-history-analyzer"
version = "0.1.0"
authors = ["Radek Micek <radek.micek@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["unbounded_depth"] }
